//
// Created by nader on 2022-02-06.
//

#ifndef TEAM_DEBUGS_H
#define TEAM_DEBUGS_H

#define DEBUG_UNMARK

//#define DEBUG_MARK_MATCH_FINDER
//
//#define DEBUG_BLOCK
//
//#define DEBUG_MARK_DECISION_GREEDY
//
//#define DEBUG_MARK_DECISIONS
//
//#define DEBUG_MARK_EXECUTE
//
//#define DEBUG_POSITION_FINDER

//#define DEBUG_NECK_DECISION


#define DEBUG_PASS_TIME_CALC
#define DEBUG_PASS
#define DEBUG_PASS_UPDATE_PASSER
#define DEBUG_PASS_UPDATE_RECEIVERS
#define DEBUG_PASS_UPDATE_OPPONENT
#define DEBUG_PASS_OPPONENT_REACH_STEP

#define DEBUG_ACTION_DENOISER

#endif //TEAM_DEBUGS_H
